name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main   # 👈 o la rama que uses para producción

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build --if-present

      - name: Deploy to Firebase Hosting
        run: npx firebase deploy --only hosting:solkos-coolview-2-qa --token "$FIREBASE_TOKEN"
